version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "hex"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "7700:3306"

  grpc:
    build: .
    environment:
      DB_DRIVER: "mysql"
      DB_SOURCE: "root:secret@tcp(db:3306)/hex"
    depends_on:
      - db
